theme: jekyll-theme-slate

title: "Decay Replay Mining - A ProM Plugin"
description: "Enhancing Petri nets with Time Decay Functions and Extracting Timed State Samples using Decay Replay Mining (DREAM)"

show_downloads: False
